### ISSUE TITLE
convents vs. conv nets

### ISSUE THREAD

**Issue by rcox771** [keplr-io/quiver#50]
small typo in [setup.py](https://github.com/keplr-io/quiver/blob/master/setup.py)

description=("Interactive per-layer visualization for [convents](https://user-images.githubusercontent.com/13604961/27208599-962927d8-5214-11e7-9425-89e25c4cb618.png) in keras"),

![image](https://user-images.githubusercontent.com/13604961/27208599-962927d8-5214-11e7-9425-89e25c4cb618.png)

**Comment by jakebian** [comment]
Nice. Wanna send a PR?
