### ISSUE TITLE
wrong number of feature maps?

### ISSUE THREAD

**Issue by lesley9309** [keplr-io/quiver#65]
Hello,

Recently, I used the Quiver to visualized my simple ConvNet. However, I got weird output images. 
For example, my network has 64 filters in the first conv layer. In my opinion, it should show 64 feature maps using the Quiver when I choose that layer, no? But I got 28 images when I train the mnist dataset, which is the height of the image. I check the size and I got (28,28,64).
At the same time, when I use the imagenet, it shows 224 images for the conv1 layer instead of 64 feature maps, where the size of this layer is (224,224,64).
Therefore, I'm just wondering if the app takes the wrong number as the number of images. Otherwise, what do the images shows using Quiver for each layer?
If someone knows the reason, it will be a great appreciate ! Thank you.

model = VGG16(include_top=True, weights='imagenet')
server.launch(
        model,
        top=5,
        temp_folder='./tmp',
        input_folder='imgs/',
        port=5000)

**Comment by jakebian** [comment]
May help if you link to your model code, have seen similar issues with input preprocessing but not with middle layers.

**Comment by sodaGH** [comment]
@lesley9309 @jakebian  Sorry to bother you. I want to do the visualization on my own model, but now I have problem running the demo. I first create an environment of python 3.5 by anaconda, and then get into the directory and installed the quiver by pip install quiver_engine . After that, I open the python and imported keras, when I run from quiver_engine import server, an error exist, it tells that:
![selection_014](https://user-images.githubusercontent.com/18156614/40593417-fe29a0a6-6217-11e8-888e-3d4bd4fd1bf2.png)

I can't find the 'gevent.wsgi' file under the quiver_master directory. Could you please tell me how you run the demo and your own model?
Do thanks a lot !!!

**Comment by lesley9309** [comment]
Hi, I installed the Quiver in the same way. And it works for me.
I think you should install the gevent library which is not included inside
the Quiver.

FYI

# Copyright (c) 2009-2012 Denis Bilenko. See LICENSE for details.
"""
gevent is a coroutine-based Python networking library that uses greenlet
to provide a high-level synchronous API on top of libev event loop.

See http://www.gevent.org/ for the documentation.
"""

May it could help!

2018-05-28 3:39 GMT+02:00 sodaGH <notifications@github.com>:

**Comment by lesley9309** [comment]
@jakebian I set the data_format='channels_last' for all layers, then it works for me now. The input layer has 3 features with 224x224 resolution
