### ISSUE TITLE
when I import server, there comes the error, no module named 'gevent.wsgi'

### ISSUE THREAD

**Issue by cherrylawrence** [keplr-io/quiver#71]
from quiver_engine import server

ImportError                               Traceback (most recent call last)
<ipython-input-11-f7d8f00ca058> in <module>()
----> 1 from quiver_engine import server

~\Anaconda3\envs\tensorflow\lib\site-packages\quiver_engine\server.py in <module>()
     11 from flask_cors import CORS
     12 
---> 13 from gevent.wsgi import WSGIServer
     14 
     15 from quiver_engine.util import (

ImportError: No module named 'gevent.wsgi'

**Comment by jakebian** [comment]
Try (re)installing gevent?

**Comment by jmgo** [comment]
I had the same problem and I fixed by changing 

from gevent.wsgi import WSGIServer
to 
from gevent.pywsgi import WSGIServer

**Comment by jakebian** [comment]
Should be fixed by the newly merged PR

**Comment by jakebian** [comment]
https://github.com/keplr-io/quiver/pull/72
